<?php

namespace Database\Seeders;

use App\Models\City;
use App\Models\Province;
use Illuminate\Database\Seeder;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds for ALL 38 Indonesian Provinces and Cities/Regencies.
     */
    public function run(): void
    {
        $data = [
            'Aceh' => [
                'Kota Banda Aceh',
                'Kota Sabang',
                'Kota Lhokseumawe',
                'Kota Langsa',
                'Kota Subulussalam',
                'Kabupaten Aceh Besar',
                'Kabupaten Aceh Tengah',
                'Kabupaten Aceh Utara',
                'Kabupaten Aceh Timur',
                'Kabupaten Aceh Selatan',
                'Kabupaten Aceh Barat',
                'Kabupaten Aceh Singkil',
                'Kabupaten Bener Meriah',
                'Kabupaten Pidie',
                'Kabupaten Bireuen',
            ],
            'Sumatera Utara' => [
                'Kota Medan',
                'Kota Pematangsiantar',
                'Kota Binjai',
                'Kota Tebing Tinggi',
                'Kota Padangsidimpuan',
                'Kota Sibolga',
                'Kota Gunungsitoli',
                'Kota Tanjungbalai',
                'Kabupaten Simalungun',
                'Kabupaten Karo',
                'Kabupaten Deli Serdang',
                'Kabupaten Serdang Bedagai',
                'Kabupaten Asahan',
                'Kabupaten Labuhanbatu',
                'Kabupaten Toba',
                'Kabupaten Samosir',
                'Kabupaten Tapanuli Utara',
                'Kabupaten Dairi',
                'Kabupaten Humbang Hasundutan',
                'Kabupaten Nias',
            ],
            'Sumatera Barat' => [
                'Kota Padang',
                'Kota Bukittinggi',
                'Kota Payakumbuh',
                'Kota Solok',
                'Kota Pariaman',
                'Kota Sawahlunto',
                'Kota Padang Panjang',
                'Kabupaten Agam',
                'Kabupaten Tanah Datar',
                'Kabupaten Pasaman',
                'Kabupaten Pesisir Selatan',
            ],
            'Riau' => [
                'Kota Pekanbaru',
                'Kota Dumai',
                'Kabupaten Kampar',
                'Kabupaten Bengkalis',
                'Kabupaten Siak',
                'Kabupaten Indragiri Hulu',
                'Kabupaten Indragiri Hilir',
                'Kabupaten Rokan Hulu',
                'Kabupaten Rokan Hilir',
            ],
            'Kepulauan Riau' => [
                'Kota Batam',
                'Kota Tanjungpinang',
                'Kabupaten Bintan',
                'Kabupaten Karimun',
                'Kabupaten Natuna',
                'Kabupaten Lingga',
                'Kabupaten Anambas',
            ],
            'Jambi' => [
                'Kota Jambi',
                'Kota Sungai Penuh',
                'Kabupaten Muaro Jambi',
                'Kabupaten Bungo',
                'Kabupaten Tebo',
                'Kabupaten Merangin',
                'Kabupaten Kerinci',
            ],
            'Sumatera Selatan' => [
                'Kota Palembang',
                'Kota Prabumulih',
                'Kota Lubuklinggau',
                'Kota Pagar Alam',
                'Kabupaten Ogan Komering Ilir',
                'Kabupaten Muara Enim',
                'Kabupaten Musi Banyuasin',
            ],
            'Bangka Belitung' => [
                'Kota Pangkalpinang',
                'Kabupaten Bangka',
                'Kabupaten Belitung',
                'Kabupaten Bangka Barat',
                'Kabupaten Bangka Selatan',
                'Kabupaten Belitung Timur',
            ],
            'Bengkulu' => [
                'Kota Bengkulu',
                'Kabupaten Rejang Lebong',
                'Kabupaten Bengkulu Utara',
                'Kabupaten Bengkulu Selatan',
            ],
            'Lampung' => [
                'Kota Bandar Lampung',
                'Kota Metro',
                'Kabupaten Lampung Selatan',
                'Kabupaten Lampung Tengah',
                'Kabupaten Lampung Utara',
                'Kabupaten Pesawaran',
                'Kabupaten Tanggamus',
            ],
            'DKI Jakarta' => [
                'Kota Jakarta Selatan',
                'Kota Jakarta Pusat',
                'Kota Jakarta Barat',
                'Kota Jakarta Timur',
                'Kota Jakarta Utara',
                'Kabupaten Kepulauan Seribu',
            ],
            'Banten' => [
                'Kota Tangerang',
                'Kota Tangerang Selatan',
                'Kota Serang',
                'Kota Cilegon',
                'Kabupaten Tangerang',
                'Kabupaten Serang',
                'Kabupaten Lebak',
                'Kabupaten Pandeglang',
            ],
            'Jawa Barat' => [
                'Kota Bandung',
                'Kota Bogor',
                'Kota Depok',
                'Kota Bekasi',
                'Kota Cimahi',
                'Kota Cirebon',
                'Kota Sukabumi',
                'Kota Tasikmalaya',
                'Kota Banjar',
                'Kabupaten Bandung',
                'Kabupaten Bogor',
                'Kabupaten Bekasi',
                'Kabupaten Sumedang',
                'Kabupaten Garut',
                'Kabupaten Cianjur',
                'Kabupaten Subang',
                'Kabupaten Karawang',
                'Kabupaten Purwakarta',
                'Kabupaten Majalengka',
                'Kabupaten Indramayu',
                'Kabupaten Ciamis',
            ],
            'Jawa Tengah' => [
                'Kota Semarang',
                'Kota Surakarta (Solo)',
                'Kota Magelang',
                'Kota Salatiga',
                'Kota Pekalongan',
                'Kota Tegal',
                'Kabupaten Banyumas',
                'Kabupaten Kudus',
                'Kabupaten Sragen',
                'Kabupaten Cilacap',
                'Kabupaten Brebes',
                'Kabupaten Pati',
                'Kabupaten Jepara',
                'Kabupaten Wonosobo',
                'Kabupaten Karanganyar',
                'Kabupaten Sukoharjo',
            ],
            'DI Yogyakarta' => [
                'Kota Yogyakarta',
                'Kabupaten Sleman',
                'Kabupaten Bantul',
                'Kabupaten Gunungkidul',
                'Kabupaten Kulon Progo',
            ],
            'Jawa Timur' => [
                'Kota Surabaya',
                'Kota Malang',
                'Kota Kediri',
                'Kota Madiun',
                'Kota Mojokerto',
                'Kota Pasuruan',
                'Kota Probolinggo',
                'Kota Blitar',
                'Kota Batu',
                'Kabupaten Sidoarjo',
                'Kabupaten Gresik',
                'Kabupaten Banyuwangi',
                'Kabupaten Jember',
                'Kabupaten Lamongan',
                'Kabupaten Tuban',
                'Kabupaten Bojonegoro',
            ],
            'Bali' => [
                'Kota Denpasar',
                'Kabupaten Badung',
                'Kabupaten Gianyar',
                'Kabupaten Tabanan',
                'Kabupaten Buleleng',
                'Kabupaten Klungkung',
                'Kabupaten Karangasem',
                'Kabupaten Bangli',
                'Kabupaten Jembrana',
            ],
            'Nusa Tenggara Barat (NTB)' => [
                'Kota Mataram',
                'Kota Bima',
                'Kabupaten Lombok Barat',
                'Kabupaten Lombok Tengah',
                'Kabupaten Lombok Timur',
                'Kabupaten Lombok Utara',
                'Kabupaten Sumbawa',
                'Kabupaten Sumbawa Barat',
                'Kabupaten Dompu',
                'Kabupaten Bima',
            ],
            'Nusa Tenggara Timur (NTT)' => [
                'Kota Kupang',
                'Kabupaten Manggarai',
                'Kabupaten Manggarai Barat (Labuan Bajo)',
                'Kabupaten Ende',
                'Kabupaten Sikka',
                'Kabupaten Sumba Barat',
                'Kabupaten Sumba Timur',
                'Kabupaten Belu',
            ],
            'Kalimantan Barat' => [
                'Kota Pontianak',
                'Kota Singkawang',
                'Kabupaten Kubu Raya',
                'Kabupaten Mempawah',
                'Kabupaten Sambas',
                'Kabupaten Sintang',
                'Kabupaten Ketapang',
            ],
            'Kalimantan Tengah' => [
                'Kota Palangka Raya',
                'Kabupaten Kotawaringin Barat',
                'Kabupaten Kotawaringin Timur',
                'Kabupaten Kapuas',
                'Kabupaten Barito Selatan',
            ],
            'Kalimantan Selatan' => [
                'Kota Banjarmasin',
                'Kota Banjarbaru',
                'Kabupaten Banjar',
                'Kabupaten Tanah Laut',
                'Kabupaten Kotabaru',
                'Kabupaten Tabalong',
            ],
            'Kalimantan Timur' => [
                'Kota Samarinda',
                'Kota Balikpapan',
                'Kota Bontang',
                'Kabupaten Kutai Kartanegara',
                'Kabupaten Berau',
                'Kabupaten Paser',
                'Kabupaten Penajam Paser Utara',
            ],
            'Kalimantan Utara' => [
                'Kota Tarakan',
                'Kabupaten Bulungan',
                'Kabupaten Nunukan',
                'Kabupaten Malinau',
                'Kabupaten Tana Tidung',
            ],
            'Sulawesi Utara' => [
                'Kota Manado',
                'Kota Bitung',
                'Kota Tomohon',
                'Kota Kotamobagu',
                'Kabupaten Minahasa',
                'Kabupaten Minahasa Utara',
                'Kabupaten Minahasa Selatan',
                'Kabupaten Kepulauan Sangihe',
            ],
            'Gorontalo' => [
                'Kota Gorontalo',
                'Kabupaten Gorontalo',
                'Kabupaten Bone Bolango',
                'Kabupaten Pohuwato',
                'Kabupaten Boalemo',
            ],
            'Sulawesi Tengah' => [
                'Kota Palu',
                'Kabupaten Poso',
                'Kabupaten Donggala',
                'Kabupaten Banggai',
                'Kabupaten Tolitoli',
                'Kabupaten Parigi Moutong',
            ],
            'Sulawesi Barat' => [
                'Kabupaten Mamuju',
                'Kabupaten Polewali Mandar',
                'Kabupaten Majene',
                'Kabupaten Mamasa',
                'Kabupaten Pasangkayu',
            ],
            'Sulawesi Selatan' => [
                'Kota Makassar',
                'Kota Parepare',
                'Kota Palopo',
                'Kabupaten Gowa',
                'Kabupaten Maros',
                'Kabupaten Bone',
                'Kabupaten Bulukumba',
                'Kabupaten Toraja Utara',
                'Kabupaten Tana Toraja',
                'Kabupaten Luwu',
            ],
            'Sulawesi Tenggara' => [
                'Kota Kendari',
                'Kota Baubau',
                'Kabupaten Kolaka',
                'Kabupaten Konawe',
                'Kabupaten Muna',
                'Kabupaten Wakatobi',
            ],
            'Maluku' => [
                'Kota Ambon',
                'Kota Tual',
                'Kabupaten Maluku Tengah',
                'Kabupaten Maluku Tenggara',
                'Kabupaten Buru',
                'Kabupaten Seram Bagian Barat',
            ],
            'Maluku Utara' => [
                'Kota Ternate',
                'Kota Tidore Kepulauan',
                'Kabupaten Halmahera Utara',
                'Kabupaten Halmahera Selatan',
                'Kabupaten Halmahera Barat',
            ],
            'Papua' => [
                'Kota Jayapura',
                'Kabupaten Jayapura',
                'Kabupaten Keerom',
                'Kabupaten Sarmi',
            ],
            'Papua Barat' => [
                'Kota Sorong',
                'Kabupaten Manokwari',
                'Kabupaten Teluk Bintuni',
                'Kabupaten Fakfak',
                'Kabupaten Kaimana',
            ],
            'Papua Barat Daya' => [
                'Kota Sorong',
                'Kabupaten Raja Ampat',
                'Kabupaten Sorong',
                'Kabupaten Sorong Selatan',
            ],
            'Papua Selatan' => [
                'Kabupaten Merauke',
                'Kabupaten Asmat',
                'Kabupaten Mappi',
                'Kabupaten Boven Digoel',
            ],
            'Papua Tengah' => [
                'Kabupaten Nabire',
                'Kabupaten Mimika (Timika)',
                'Kabupaten Puncak Jaya',
                'Kabupaten Paniai',
            ],
            'Papua Pegunungan' => [
                'Kabupaten Jayawijaya (Wamena)',
                'Kabupaten Lanny Jaya',
                'Kabupaten Nduga',
                'Kabupaten Yahukimo',
            ],
        ];

        foreach ($data as $provinceName => $cities) {
            $province = Province::firstOrCreate(['name' => $provinceName]);

            foreach ($cities as $cityName) {
                City::firstOrCreate([
                    'province_id' => $province->id,
                    'name' => $cityName,
                ]);
            }
        }
    }
}
